# Generated by Django 5.1.4 on 2024-12-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_category_city_alter_ad_image_ad_category_ad_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(default='default_category', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(default='default_city', max_length=10),
        ),
    ]
