# Generated by Django 5.1.4 on 2024-12-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_category_city_alter_ad_category_alter_ad_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ads.city'),
        ),
    ]
